namespace Bizland.Utilities.Enums
{
    public enum MobileResourceNames
    {
        #region Common

        Common_Label_BAGPS,
        Common_NoInternet,
        Common_Lable_All,
        Common_Lable_More,
        Common_Lable_NotFound,
        Common_Lable_ChooseCompany,
        Common_Loading_Processing1,
        Common_Lable_ChooseVehicleGroup,
        Common_Message_Loading,
        Common_Message_Warning,
        Common_Message_Skip,
        Common_Button_OK,
        Common_Button_Send,
        Common_Button_Save,
        Common_Button_View,
        Common_Button_Cancel,
        Common_Button_Yes,
        Common_Button_No,
        Common_Button_Close,
        Common_Message_ErrorTryAgain,
        Common_Message_SearchText,
        Common_Message_SearchTextValid,
        Common_Label_CameraTitle,
        Common_Label_Year,
        Common_Label_Month,
        Common_Label_Day,
        Common_Label_Day2,
        Common_Label_Hour,
        Common_Label_Hour2,
        Common_Label_Minute,
        Common_Label_Minute2,
        Common_Label_Second,
        Common_Label_Duration,
        Common_Label_Duration2,
        Common_Message_CameraUnavailable,
        Common_Message_CameraUnsupported,
        Common_Message_PickPhotoUnsupported,
        Common_Message_PickPhotoPermissionNotGranted,
        Common_Message_ViewAvatar,
        Common_Message_TakeNewPhoto,
        Common_Message_ChooseAvailablePhotos,
        Common_Button_Update,
        Common_Value_SelectGender,
        Common_Value_SelectReligion,
        Common_Lable_Car,
        Common_Label_Vehicle,
        Common_Lable_KmUnit,
        Common_Lable_NMUnit,
        Common_Property_Invalid,
        Common_Property_NullOrEmpty,
        Common_Property_MinLength,
        Common_Property_DangerousChars,
        Common_Property_NotContainChars,
        Common_Property_DangerousCharShow,
        Common_Message_RequiredNullOrEmpty,
        Common_Label_TitleGrid_VehiclePlate,
        Common_Label_TitleGrid_OrderNumber,
        Common_Label_Time,
        Common_Label_Close,
        Common_Label_Open,
        Common_Label_TurnOn,
        Common_Label_TurnOff,
        Common_Label_Craning,
        Common_Label_Normal,
        Common_Label_Lowerben,
        Common_Label_LoweredBen,
        Common_Message_SelectCompany,
        Common_Message_NotFindYourCar,
        Common_Message_LoadMore,
        Common_Label_DoorClose,
        Common_Label_DoorOpen,

        #endregion Common

        #region datetimepicker

        Common_Label_TimePicker,
        Common_Label_DatePicker,

        #endregion datetimepicker
    }
}